/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.18.1
 *
 * Copyright (c) 2015 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt4.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtHelp.h"

#line 51 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/sip/QtHelp/qhelpindexwidget.sip"
#include <qhelpindexwidget.h>
#line 29 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"

#line 31 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 33 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 28 "sip/QtCore/qmap.sip"
#include <qmap.h>
#line 36 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 72 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 39 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 102 "sip/QtCore/qurl.sip"
#include <qurl.h>
#line 42 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtCore/qabstractitemmodel.sip"
#include <qabstractitemmodel.h>
#line 45 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 169 "sip/QtGui/qitemselectionmodel.sip"
#include <qitemselectionmodel.h>
#line 48 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 28 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 51 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qregion.sip"
#include <qregion.h>
#line 54 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qrect.sip"
#include <qrect.h>
#line 57 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 89 "sip/QtGui/qitemselectionmodel.sip"
#include <qitemselectionmodel.h>
#line 60 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qpoint.sip"
#include <qpoint.h>
#line 63 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qabstractitemview.sip"
#include <qabstractitemview.h>
#line 66 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 69 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 528 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 72 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 1130 "sip/QtGui/qstyleoption.sip"
#include <qstyleoption.h>
#line 75 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 78 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 743 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 81 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 796 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 84 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 769 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 87 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 565 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 90 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 351 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 93 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 256 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 96 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 99 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qlistview.sip"
#include <qlistview.h>
#line 102 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qsize.sip"
#include <qsize.h>
#line 105 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 108 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 651 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 111 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 269 "sip/QtCore/qvariant.sip"
#include <qvariant.h>
#line 114 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qabstractitemdelegate.sip"
#include <qabstractitemdelegate.h>
#line 117 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 478 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 120 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 509 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 123 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 785 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 126 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 29 "sip/QtCore/qobject.sip"
#include <qobject.h>
#line 129 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 32 "sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 132 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qabstractitemview.sip"
#include <qabstractitemview.h>
#line 135 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 89 "sip/QtGui/qitemselectionmodel.sip"
#include <qitemselectionmodel.h>
#line 138 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 122 "sip/QtCore/qabstractitemmodel.sip"
#include <qabstractitemmodel.h>
#line 141 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 115 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 144 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 147 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qscrollbar.sip"
#include <qscrollbar.h>
#line 150 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 622 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 153 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 351 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 156 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 34 "sip/QtCore/qmargins.sip"
#include <qmargins.h>
#line 159 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qpainter.sip"
#include <qpainter.h>
#line 162 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qframe.sip"
#include <qframe.h>
#line 165 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 168 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 171 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 34 "sip/QtGui/qgraphicseffect.sip"
#include <qgraphicseffect.h>
#line 174 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 28 "sip/QtGui/qgraphicsproxywidget.sip"
#include <qgraphicsproxywidget.h>
#line 177 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qlocale.sip"
#include <qlocale.h>
#line 180 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qpaintdevice.sip"
#include <qpaintdevice.h>
#line 183 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 32 "sip/QtGui/qwidget.sip"
#include <qwidget.h>
#line 186 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 32 "sip/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 189 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qfontinfo.sip"
#include <qfontinfo.h>
#line 192 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qfontmetrics.sip"
#include <qfontmetrics.h>
#line 195 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qfont.sip"
#include <qfont.h>
#line 198 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 201 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qpalette.sip"
#include <qpalette.h>
#line 204 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 611 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 207 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 600 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 210 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 858 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 213 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 407 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 216 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 578 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 219 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 552 "sip/QtGui/qevent.sip"
#include <qevent.h>
#line 222 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 28 "sip/QtGui/qinputcontext.sip"
#include <qinputcontext.h>
#line 225 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 56 "sip/QtGui/qpaintengine.sip"
#include <qpaintengine.h>
#line 228 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 115 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 231 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qaction.sip"
#include <qaction.h>
#line 234 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtGui/qlayout.sip"
#include <qlayout.h>
#line 237 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qsizepolicy.sip"
#include <qsizepolicy.h>
#line 240 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 243 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qkeysequence.sip"
#include <qkeysequence.h>
#line 246 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qcursor.sip"
#include <qcursor.h>
#line 249 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qicon.sip"
#include <qicon.h>
#line 252 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qbitmap.sip"
#include <qbitmap.h>
#line 255 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtGui/qstyle.sip"
#include <qstyle.h>
#line 258 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 368 "sip/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 261 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 28 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 264 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 115 "sip/QtCore/qlist.sip"
#include <qlist.h>
#line 267 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtCore/qthread.sip"
#include <qthread.h>
#line 270 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 30 "sip/QtCore/qregexp.sip"
#include <qregexp.h>
#line 273 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"
#line 26 "sip/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 276 "/Users/behdad/Documents/Visual_Analytics_WS16-17/lib/PyQt-mac-gpl-4.11.4/QtHelp/sipQtHelpQHelpIndexWidget.cpp"


PyDoc_STRVAR(doc_QHelpIndexWidget_filterIndices, "filterIndices(self, QString, wildcard: QString = QString())");

extern "C" {static PyObject *meth_QHelpIndexWidget_filterIndices(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_QHelpIndexWidget_filterIndices(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        const QString* a0;
        int a0State = 0;
        const QString& a1def = QString();
        const QString* a1 = &a1def;
        int a1State = 0;
        QHelpIndexWidget *sipCpp;

        static const char *sipKwdList[] = {
            NULL,
            sipName_wildcard,
        };

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, sipKwdList, NULL, "BJ1|J1", &sipSelf, sipType_QHelpIndexWidget, &sipCpp, sipType_QString,&a0, &a0State, sipType_QString,&a1, &a1State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->filterIndices(*a0,*a1);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);
            sipReleaseType(const_cast<QString *>(a1),sipType_QString,a1State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpIndexWidget, sipName_filterIndices, doc_QHelpIndexWidget_filterIndices);

    return NULL;
}


PyDoc_STRVAR(doc_QHelpIndexWidget_activateCurrentItem, "activateCurrentItem(self)");

extern "C" {static PyObject *meth_QHelpIndexWidget_activateCurrentItem(PyObject *, PyObject *);}
static PyObject *meth_QHelpIndexWidget_activateCurrentItem(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        QHelpIndexWidget *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QHelpIndexWidget, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->activateCurrentItem();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QHelpIndexWidget, sipName_activateCurrentItem, doc_QHelpIndexWidget_activateCurrentItem);

    return NULL;
}


/* Cast a pointer to a type somewhere in its multiple inheritance hierarchy. */
extern "C" {static void *cast_QHelpIndexWidget(void *, const sipTypeDef *);}
static void *cast_QHelpIndexWidget(void *sipCppV, const sipTypeDef *targetType)
{
    QHelpIndexWidget *sipCpp = reinterpret_cast<QHelpIndexWidget *>(sipCppV);

    if (targetType == sipType_QPaintDevice)
        return static_cast<QPaintDevice *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_QHelpIndexWidget(void *, int);}
static void release_QHelpIndexWidget(void *sipCppV,int)
{
    QHelpIndexWidget *sipCpp = reinterpret_cast<QHelpIndexWidget *>(sipCppV);

    Py_BEGIN_ALLOW_THREADS

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_QHelpIndexWidget(sipSimpleWrapper *);}
static void dealloc_QHelpIndexWidget(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QHelpIndexWidget(sipGetAddress(sipSelf),0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QHelpIndexWidget[] = {{314, 1, 1}};


static PyMethodDef methods_QHelpIndexWidget[] = {
    {SIP_MLNAME_CAST(sipName_activateCurrentItem), meth_QHelpIndexWidget_activateCurrentItem, METH_VARARGS, SIP_MLDOC_CAST(doc_QHelpIndexWidget_activateCurrentItem)},
    {SIP_MLNAME_CAST(sipName_filterIndices), (PyCFunction)meth_QHelpIndexWidget_filterIndices, METH_VARARGS|METH_KEYWORDS, SIP_MLDOC_CAST(doc_QHelpIndexWidget_filterIndices)}
};


/* Define this type's signals. */
static const pyqt4QtSignal signals_QHelpIndexWidget[] = {
    {"linksActivated(QMap<QString,QUrl>,QString)", "\1linksActivated(self, object, QString)", 0, 0},
    {"linkActivated(QUrl,QString)", "\1linkActivated(self, QUrl, QString)", 0, 0},
    {0, 0, 0, 0}
};


pyqt4ClassTypeDef sipTypeDef_QtHelp_QHelpIndexWidget = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_QHelpIndexWidget,
        {0}
    },
    {
        sipNameNr_QHelpIndexWidget,
        {0, 0, 1},
        2, methods_QHelpIndexWidget,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QHelpIndexWidget,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QHelpIndexWidget,
    0,
    0,
    0,
    release_QHelpIndexWidget,
    cast_QHelpIndexWidget,
    0,
    0,
    0,
    0,
    0,
    0
},
    &QHelpIndexWidget::staticMetaObject,
    0,
    signals_QHelpIndexWidget,
};
